CREATE TABLE IF NOT EXISTS EB_USER (
    USER_ID     VARCHAR(50) PRIMARY KEY,
    USER_NAME   VARCHAR(100),
    BRANCH_ID   VARCHAR(20),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EB_EVENT (
    EVENT_ID      VARCHAR(50) PRIMARY KEY,
    USER_ID       VARCHAR(50) NOT NULL,
    EVENT_TYPE    VARCHAR(30) NOT NULL,
    EVENT_STATUS  VARCHAR(20) NOT NULL,
    RETRY_COUNT   INT DEFAULT 0,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SENT_AT       TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_EB_EVENT_STATUS ON EB_EVENT (EVENT_STATUS, CREATED_AT);
