-- tcf-oc Hello World 샘플 (eb-service schema.sql 패턴)

CREATE TABLE IF NOT EXISTS CP_HELLO_LOG (
    LOG_ID      VARCHAR(50) PRIMARY KEY,
    NAME        VARCHAR(100),
    MESSAGE     VARCHAR(200),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_CAPACITY_ACCOUNT (
    ACCOUNT_NUMBER         VARCHAR(30)  NOT NULL PRIMARY KEY,
    NAME                   VARCHAR(100),
    IDENTIFICATION_NUMBER  VARCHAR(20),
    INTEREST_RATE          DOUBLE,
    LAST_TRANSACTION       TIMESTAMP,
    PASSWORD               VARCHAR(100),
    NET_AMOUNT             DOUBLE,
    ACCOUNT_TYPE           VARCHAR(20),
    STATUS                 VARCHAR(20),
    CURRENCY               VARCHAR(10),
    CREATED_DATE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
