CREATE TABLE IF NOT EXISTS TCF_GATEWAY_ROUTE (
    ROUTE_ID             VARCHAR(60)  NOT NULL,
    ENV_CODE             VARCHAR(20)  NOT NULL,
    ROUTE_GROUP_CODE     VARCHAR(30)  NOT NULL,
    ROUTE_GROUP_NAME     VARCHAR(100) NOT NULL,
    BUSINESS_CODE        VARCHAR(10)  NOT NULL,
    BUSINESS_NAME        VARCHAR(100) NOT NULL,
    TARGET_BASE_URL      VARCHAR(300) NOT NULL,
    CONTEXT_PATH         VARCHAR(100) NOT NULL,
    ONLINE_PATH          VARCHAR(100) DEFAULT '/online' NOT NULL,
    HEALTH_CHECK_PATH    VARCHAR(200),
    CONNECT_TIMEOUT_MS   INT DEFAULT 3000 NOT NULL,
    READ_TIMEOUT_MS      INT DEFAULT 5000 NOT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y' NOT NULL,
    SORT_ORDER           INT,
    DESCRIPTION          VARCHAR(500),
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP,
    CONSTRAINT PK_TCF_GATEWAY_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT UK_TCF_GATEWAY_ROUTE_01 UNIQUE (ENV_CODE, BUSINESS_CODE)
);

CREATE INDEX IF NOT EXISTS IX_TCF_GATEWAY_ROUTE_01 ON TCF_GATEWAY_ROUTE (ENV_CODE, BUSINESS_CODE, USE_YN);
CREATE INDEX IF NOT EXISTS IX_TCF_GATEWAY_ROUTE_02 ON TCF_GATEWAY_ROUTE (ENV_CODE, ROUTE_GROUP_CODE, USE_YN);
