server:
  port: 8099
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: nsight-tcf-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

nsight:
  tcf-ui:
    deployment-mode: bootrun
    tomcat-gateway-url: http://localhost:8080
    bootrun-host: http://127.0.0.1
