CREATE INDEX IX_HAR_BASELINE_PROJECT ON HAR_BASELINE(PROJECT_ID,STATUS_CODE);
CREATE INDEX IX_HAR_RUN_PROJECT_STATUS ON HAR_RUN(PROJECT_ID,STATUS_CODE,CREATED_AT DESC);
CREATE INDEX IX_HAR_STAGE_RUN_ORDER ON HAR_RUN_STAGE(RUN_ID,STAGE_ORDER);
CREATE INDEX IX_HAR_STEP_STAGE_ORDER ON HAR_RUN_STEP(RUN_STAGE_ID,STEP_ORDER);
CREATE INDEX IX_HAR_TASK_STATUS_READY ON HAR_AGENT_TASK(STATUS_CODE,READY_AT);
CREATE INDEX IX_HAR_TASK_RUN ON HAR_AGENT_TASK(RUN_ID,STATUS_CODE);
CREATE INDEX IX_HAR_TASK_LEASE ON HAR_AGENT_TASK(LEASE_EXPIRES_AT,STATUS_CODE);
CREATE INDEX IX_HAR_ATTEMPT_TASK ON HAR_TASK_ATTEMPT(TASK_ID,ATTEMPT_NO DESC);
CREATE INDEX IX_HAR_CP_RUN ON HAR_CHECKPOINT(RUN_ID,CREATED_AT DESC);
CREATE UNIQUE INDEX UX_HAR_LOCK_ACTIVE ON HAR_RESOURCE_LOCK(
 CASE WHEN RELEASED_AT IS NULL THEN RESOURCE_TYPE END,
 CASE WHEN RELEASED_AT IS NULL THEN RESOURCE_ID END,
 CASE WHEN RELEASED_AT IS NULL THEN LOCK_MODE END
);
CREATE INDEX IX_HAR_ART_RUN_TYPE ON HAR_ARTIFACT(RUN_ID,ARTIFACT_TYPE,STATUS_CODE);
CREATE INDEX IX_HAR_ART_VER_HASH ON HAR_ARTIFACT_VER(CONTENT_HASH);
CREATE INDEX IX_HAR_MAN_RUN_STAGE ON HAR_MANIFEST(RUN_ID,STAGE_ID,STATUS_CODE);
CREATE INDEX IX_HAR_REQ_RUN_STATUS ON HAR_REQUIREMENT(RUN_ID,STATUS_CODE,PRIORITY_CODE);
CREATE INDEX IX_HAR_SVC_RUN_BUSINESS ON HAR_SERVICE_DEF(RUN_ID,BUSINESS_CODE,STATUS_CODE);
CREATE INDEX IX_HAR_PC_SVC_TYPE ON HAR_PROGRAM_COMP(SERVICE_DEF_ID,COMPONENT_TYPE);
CREATE INDEX IX_HAR_SQL_SVC ON HAR_SQL_STMT(SERVICE_DEF_ID,OPERATION_TYPE);
CREATE INDEX IX_HAR_TRACE_SOURCE ON HAR_TRACE_LINK(RUN_ID,SOURCE_TYPE,SOURCE_ID);
CREATE INDEX IX_HAR_TRACE_TARGET ON HAR_TRACE_LINK(RUN_ID,TARGET_TYPE,TARGET_ID);
CREATE INDEX IX_HAR_EE_RUN_TYPE ON HAR_EXEC_EVIDENCE(RUN_ID,EVIDENCE_TYPE);
CREATE INDEX IX_HAR_GR_RUN_GATE ON HAR_GATE_RESULT(RUN_ID,GATE_ID,EVALUATED_AT DESC);
CREATE INDEX IX_HAR_APPROVAL_RUN_DEC ON HAR_APPROVAL(RUN_ID,DECISION_CODE,REQUIRED_ROLE);
CREATE INDEX IX_HAR_EXCEPTION_RULE ON HAR_EXCEPTION_APPROVAL(RULE_ID,STATUS_CODE,EXPIRES_AT);
CREATE INDEX IX_HAR_ISSUE_RUN_STATUS ON HAR_ISSUE(RUN_ID,STATUS_CODE,SEVERITY_CODE);
CREATE INDEX IX_HAR_DRIFT_RUN_STATUS ON HAR_DRIFT_ISSUE(RUN_ID,STATUS_CODE,SEVERITY_CODE);
CREATE INDEX IX_HAR_AUDIT_RUN_TIME ON HAR_AUDIT_LOG(RUN_ID,EVENT_TIME DESC);
CREATE INDEX IX_HAR_OUTBOX_PENDING ON HAR_OUTBOX_EVENT(STATUS_CODE,NEXT_RETRY_AT,OCCURRED_AT);
