package com.nh.nsight.marketing.om.support;

import org.springframework.jdbc.core.JdbcTemplate;

final class ServiceCatalogSeedData {
    private ServiceCatalogSeedData() {}

    private record Entry(
            String catalogId,
            String businessCode,
            String serviceId,
            String transactionCode,
            String processingType,
            String handlerClass,
            String authCode,
            String auditYn,
            int timeoutSec,
            String useYn,
            String description) {}

    private static final Entry[] ALL = {
            entry("CAT-001", "SV", "SV.Sample.inquiry", "SV-INQ-0001", "INQUIRY",
                    "SvSampleInquiryHandler", "ROLE_SV_INQ", "N", 5, "Y", "SV 샘플 조회"),
            entry("CAT-002", "SV", "SV.Customer.selectSummary", "SV-INQ-0002", "INQUIRY",
                    "SvCustomerSummaryHandler", "ROLE_SV_INQ", "Y", 5, "Y", "고객요약 조회"),
            entry("CAT-003", "OM", "OM.Dashboard.inquiry", "OM-DSH-0001", "INQUIRY",
                    "OmDashboardInquiryHandler", "ROLE_OM_DSH", "N", 5, "Y", "운영 대시보드"),
            entry("CAT-004", "OM", "OM.TransactionLog.inquiry", "OM-TXL-0001", "INQUIRY",
                    "OmTransactionLogInquiryHandler", "ROLE_OM_TXL", "N", 10, "Y", "거래로그 조회"),
            entry("CAT-005", "OM", "OM.ServiceCatalog.inquiry", "OM-SVC-0001", "INQUIRY",
                    "OmServiceCatalogInquiryHandler", "ROLE_OM_SVC", "N", 5, "Y", "ServiceId 카탈로그"),
            entry("CAT-009", "OM", "OM.AuditLog.inquiry", "OM-AUD-0001", "INQUIRY",
                    "OmAuditLogInquiryHandler", "ROLE_OM_AUD", "Y", 10, "Y", "감사로그 조회"),
            entry("CAT-010", "OM", "OM.ErrorCode.inquiry", "OM-ERR-0001", "INQUIRY",
                    "OmErrorCodeInquiryHandler", "ROLE_OM_ERR", "N", 5, "Y", "오류코드 조회"),
            entry("CAT-011", "OM", "OM.Batch.inquiry", "OM-BAT-0001", "INQUIRY",
                    "OmBatchInquiryHandler", "ROLE_OM_BAT", "N", 10, "Y", "배치/스케줄 조회"),
            entry("CAT-012", "OM", "OM.HealthCheck.inquiry", "OM-HLT-0001", "INQUIRY",
                    "OmHealthCheckInquiryHandler", "ROLE_OM_HLT", "N", 5, "Y", "Health Check 조회"),
            entry("CAT-013", "OM", "OM.SystemConfig.inquiry", "OM-CFG-0001", "INQUIRY",
                    "OmSystemConfigInquiryHandler", "ROLE_OM_CFG", "N", 5, "Y", "환경설정 조회"),
            entry("CAT-014", "OM", "OM.FileDownload.inquiry", "OM-FIL-0001", "INQUIRY",
                    "OmFileDownloadInquiryHandler", "ROLE_OM_FIL", "Y", 10, "Y", "파일 다운로드 이력"),
            entry("CAT-015", "OM", "OM.CommonCode.inquiry", "OM-CDC-0001", "INQUIRY",
                    "OmCommonCodeInquiryHandler", "ROLE_OM_CDC", "N", 5, "Y", "공통코드 목록 조회"),
            entry("CAT-016", "OM", "OM.CommonCode.save", "OM-CDC-0002", "UPDATE",
                    "OmCommonCodeSaveHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 등록"),
            entry("CAT-017", "OM", "OM.CommonCode.detail", "OM-CDC-0003", "INQUIRY",
                    "OmCommonCodeDetailHandler", "ROLE_OM_CDC", "N", 5, "Y", "공통코드 단건 조회"),
            entry("CAT-018", "OM", "OM.CommonCode.update", "OM-CDC-0004", "UPDATE",
                    "OmCommonCodeUpdateHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 수정"),
            entry("CAT-019", "OM", "OM.CommonCode.delete", "OM-CDC-0005", "DELETE",
                    "OmCommonCodeDeleteHandler", "ROLE_OM_CDC", "Y", 5, "Y", "공통코드 삭제"),
            entry("CAT-020", "OM", "OM.ErrorCode.save", "OM-ERR-0002", "UPDATE",
                    "OmErrorCodeSaveHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 등록"),
            entry("CAT-021", "OM", "OM.Batch.execute", "OM-BAT-0002", "EXECUTE",
                    "OmBatchExecuteHandler", "ROLE_OM_BAT", "Y", 30, "Y", "배치 재실행"),
            entry("CAT-025", "OM", "OM.Cache.inquiry", "OM-CCH-0001", "INQUIRY",
                    "OmCacheInquiryHandler", "ROLE_OM_CACHE", "N", 5, "Y", "Cache 조회"),
            entry("CAT-026", "OM", "OM.Cache.delete", "OM-CCH-0002", "DELETE",
                    "OmCacheDeleteHandler", "ROLE_OM_CACHE", "Y", 10, "Y", "Cache 삭제"),
            entry("CAT-036", "OM", "OM.TransactionLog.deleteAll", "OM-TXL-0002", "DELETE",
                    "OmTransactionLogDeleteAllHandler", "ROLE_OM_TXL", "Y", 30, "Y", "거래로그 전체 삭제"),
            entry("CAT-037", "OM", "OM.ServiceCatalog.save", "OM-SVC-0002", "UPDATE",
                    "OmServiceCatalogSaveHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 등록"),
            entry("CAT-038", "OM", "OM.ServiceCatalog.detail", "OM-SVC-0003", "INQUIRY",
                    "OmServiceCatalogDetailHandler", "ROLE_OM_SVC", "N", 5, "Y", "ServiceId 상세"),
            entry("CAT-039", "OM", "OM.ServiceCatalog.update", "OM-SVC-0004", "UPDATE",
                    "OmServiceCatalogUpdateHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 수정"),
            entry("CAT-040", "OM", "OM.ServiceCatalog.delete", "OM-SVC-0005", "DELETE",
                    "OmServiceCatalogDeleteHandler", "ROLE_OM_SVC", "Y", 5, "Y", "ServiceId 삭제"),
            entry("CAT-041", "OM", "OM.ErrorCode.detail", "OM-ERR-0003", "INQUIRY",
                    "OmErrorCodeDetailHandler", "ROLE_OM_ERR", "N", 5, "Y", "오류코드 상세"),
            entry("CAT-042", "OM", "OM.ErrorCode.update", "OM-ERR-0004", "UPDATE",
                    "OmErrorCodeUpdateHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 수정"),
            entry("CAT-043", "OM", "OM.ErrorCode.delete", "OM-ERR-0005", "DELETE",
                    "OmErrorCodeDeleteHandler", "ROLE_OM_ERR", "Y", 5, "Y", "오류코드 삭제"),
            entry("CAT-044", "OM", "OM.Batch.deleteAll", "OM-BAT-0003", "DELETE",
                    "OmBatchDeleteAllHandler", "ROLE_OM_BAT", "Y", 30, "Y", "배치 실행이력 전체 삭제"),
            entry("CAT-045", "OM", "OM.Sample.inquiry", "OM-INQ-0001", "INQUIRY",
                    "OmSampleInquiryHandler", "ROLE_OM_AUTH", "N", 5, "Y", "OM 샘플 조회"),
            entry("CAT-046", "CC", "CC.Sample.inquiry", "CC-INQ-0001", "INQUIRY",
                    "CcSampleInquiryHandler", "ROLE_CC_INQ", "N", 5, "Y", "CC 샘플 조회"),
            entry("CAT-047", "IC", "IC.Sample.inquiry", "IC-INQ-0001", "INQUIRY",
                    "IcSampleInquiryHandler", "ROLE_IC_INQ", "N", 5, "Y", "IC 샘플 조회"),
            entry("CAT-048", "PC", "PC.Sample.inquiry", "PC-INQ-0001", "INQUIRY",
                    "PcSampleInquiryHandler", "ROLE_PC_INQ", "N", 5, "Y", "PC 샘플 조회"),
            entry("CAT-049", "BC", "BC.Sample.inquiry", "BC-INQ-0001", "INQUIRY",
                    "BcSampleInquiryHandler", "ROLE_BC_INQ", "N", 5, "Y", "BC 샘플 조회"),
            entry("CAT-050", "MS", "MS.Sample.inquiry", "MS-INQ-0001", "INQUIRY",
                    "MsSampleInquiryHandler", "ROLE_MS_INQ", "N", 5, "Y", "MS 샘플 조회"),
            entry("CAT-051", "PD", "PD.Sample.inquiry", "PD-INQ-0001", "INQUIRY",
                    "PdSampleInquiryHandler", "ROLE_PD_INQ", "N", 5, "Y", "PD 샘플 조회"),
            entry("CAT-052", "CM", "CM.Sample.inquiry", "CM-INQ-0001", "INQUIRY",
                    "CmSampleInquiryHandler", "ROLE_CM_INQ", "N", 5, "Y", "CM 샘플 조회"),
            entry("CAT-053", "EB", "EB.Sample.inquiry", "EB-INQ-0001", "INQUIRY",
                    "EbSampleInquiryHandler", "ROLE_EB_INQ", "N", 5, "Y", "EB 샘플 조회"),
            entry("CAT-054", "EP", "EP.Sample.inquiry", "EP-INQ-0001", "INQUIRY",
                    "EpSampleInquiryHandler", "ROLE_EP_INQ", "N", 5, "Y", "EP 샘플 조회"),
            entry("CAT-055", "BP", "BP.Sample.inquiry", "BP-INQ-0001", "INQUIRY",
                    "BpSampleInquiryHandler", "ROLE_BP_INQ", "N", 5, "Y", "BP 샘플 조회"),
            entry("CAT-056", "BD", "BD.Sample.inquiry", "BD-INQ-0001", "INQUIRY",
                    "BdSampleInquiryHandler", "ROLE_BD_INQ", "N", 5, "Y", "BD 샘플 조회"),
            entry("CAT-057", "SS", "SS.Sample.inquiry", "SS-INQ-0001", "INQUIRY",
                    "SsSampleInquiryHandler", "ROLE_SS_INQ", "N", 5, "Y", "SS 샘플 조회"),
            entry("CAT-058", "CS", "CS.Sample.inquiry", "CS-INQ-0001", "INQUIRY",
                    "CsSampleInquiryHandler", "ROLE_CS_INQ", "N", 5, "Y", "CS 샘플 조회"),
            entry("CAT-059", "CT", "CT.Sample.inquiry", "CT-INQ-0001", "INQUIRY",
                    "CtSampleInquiryHandler", "ROLE_CT_INQ", "N", 5, "Y", "CT 샘플 조회"),
            entry("CAT-060", "MG", "MG.Sample.inquiry", "MG-INQ-0001", "INQUIRY",
                    "MgSampleInquiryHandler", "ROLE_MG_INQ", "N", 5, "Y", "MG 샘플 조회"),
            entry("CAT-061", "SV", "SV.Customer.detail", "SV-INQ-0003", "INQUIRY",
                    "SvCustomerDetailHandler", "ROLE_SV_INQ", "Y", 5, "Y", "고객 상세 조회"),
            entry("CAT-062", "SV", "SV.Customer.register", "SV-REG-0001", "CREATE",
                    "SvCustomerRegisterHandler", "ROLE_SV_INQ", "Y", 5, "Y", "고객 등록"),
            entry("CAT-063", "CM", "CM.Campaign.list", "CM-INQ-0002", "INQUIRY",
                    "CmCampaignListHandler", "ROLE_CM_INQ", "N", 5, "Y", "캠페인 목록 조회"),
            entry("CAT-064", "MG", "MG.Message.send", "MG-EXE-0001", "EXECUTE",
                    "MgMessageSendHandler", "ROLE_MG_INQ", "Y", 10, "Y", "메시지 발송"),
            entry("CAT-065", "UD", "UD.File.list", "UD-LST-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "N", 10, "Y", "파일 목록 조회"),
            entry("CAT-066", "UD", "UD.File.upload", "UD-UPL-0001", "CREATE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 30, "Y", "파일 업로드"),
            entry("CAT-067", "UD", "UD.File.download", "UD-DWN-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 30, "Y", "파일 다운로드"),
            entry("CAT-068", "UD", "UD.File.detail", "UD-DTL-0001", "INQUIRY",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "N", 5, "Y", "파일 상세 조회"),
            entry("CAT-069", "UD", "UD.File.update", "UD-UPD-0001", "UPDATE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 5, "Y", "파일 메타 수정"),
            entry("CAT-070", "UD", "UD.File.delete", "UD-DEL-0001", "DELETE",
                    "OmUpdownloadFileController", "ROLE_UD_FIL", "Y", 5, "Y", "파일 삭제"),
            entry("CAT-071", "ET", "ET.TransactionIo.list", "ET-LST-0001", "INQUIRY",
                    "EtTransactionIoListHandler", "ROLE_ET_INQ", "N", 5, "N", "거래 I/O 목록 (레거시)"),
            entry("CAT-072", "ET", "ET.TransactionIo.detail", "ET-DTL-0001", "INQUIRY",
                    "EtTransactionIoDetailHandler", "ROLE_ET_INQ", "N", 5, "N", "거래 I/O 상세 (레거시)")
    };

    static void mergeAll(JdbcTemplate jdbcTemplate) {
        for (Entry seed : ALL) {
            jdbcTemplate.update("""
                    MERGE INTO OM_SERVICE_CATALOG (CATALOG_ID, BUSINESS_CODE, SERVICE_ID, TRANSACTION_CODE,
                                                   PROCESSING_TYPE, HANDLER_CLASS, AUTH_CODE, AUDIT_YN,
                                                   TIMEOUT_SEC, USE_YN, DESCRIPTION)
                    KEY (CATALOG_ID)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    seed.catalogId(), seed.businessCode(), seed.serviceId(), seed.transactionCode(),
                    seed.processingType(), seed.handlerClass(), seed.authCode(), seed.auditYn(),
                    seed.timeoutSec(), seed.useYn(), seed.description());
        }
    }

    private static Entry entry(
            String catalogId,
            String businessCode,
            String serviceId,
            String transactionCode,
            String processingType,
            String handlerClass,
            String authCode,
            String auditYn,
            int timeoutSec,
            String useYn,
            String description) {
        return new Entry(catalogId, businessCode, serviceId, transactionCode, processingType,
                handlerClass, authCode, auditYn, timeoutSec, useYn, description);
    }
}
