INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-00','1.0.0','Input Gate','classpath:gate-rules/hg00-input.yaml','TO_BE_REPLACED','ACTIVE',0,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-10','1.0.0','Baseline Gate','classpath:gate-rules/hg10-baseline.yaml','TO_BE_REPLACED','ACTIVE',0,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-20','1.0.0','Analysis Gate','classpath:gate-rules/hg20-analysis.yaml','TO_BE_REPLACED','ACTIVE',1,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-30','1.0.0','Design Gate','classpath:gate-rules/hg30-design.yaml','TO_BE_REPLACED','ACTIVE',3,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-40','1.0.0','Implementation Gate','classpath:gate-rules/hg40-implementation.yaml','TO_BE_REPLACED','ACTIVE',0,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-50','1.0.0','Build Gate','classpath:gate-rules/hg50-build.yaml','TO_BE_REPLACED','ACTIVE',0,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-60','1.0.0','Test Gate','classpath:gate-rules/hg60-test.yaml','TO_BE_REPLACED','ACTIVE',0,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-70','1.0.0','Security and Quality Gate','classpath:gate-rules/hg70-security-quality.yaml','TO_BE_REPLACED','ACTIVE',1,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-80','1.0.0','Trace and Drift Gate','classpath:gate-rules/hg80-trace-drift.yaml','TO_BE_REPLACED','ACTIVE',1,'SYSTEM','SYSTEM');
INSERT INTO HAR_GATE_DEF(GATE_ID,GATE_VERSION,GATE_NAME,RULESET_URI,CONTENT_HASH,STATUS_CODE,REQUIRED_APPROVALS,CREATED_BY,UPDATED_BY)
VALUES('HG-90','1.0.0','Final Gate','classpath:gate-rules/hg90-final.yaml','TO_BE_REPLACED','ACTIVE',2,'SYSTEM','SYSTEM');
COMMIT;
