-- EOS P0 Physical DDL (H2) — M08 design + W0 runtime applied to src/.../db/h2/schema.sql
-- Target: pdmg-eos local H2; Oracle mapping: YMD→DATE, DTM→TIMESTAMP optional.

-- ========== DROP (dev only) ==========
DROP TABLE IF EXISTS TB_EOS_BATCH_RUN;
DROP TABLE IF EXISTS TB_EOS_CHG_HIST;
DROP TABLE IF EXISTS TB_EOS_MONTHLY_CHK;
DROP TABLE IF EXISTS TB_EOS_EXC_APPR;
DROP TABLE IF EXISTS TB_EOS_EXC_REQ;
DROP TABLE IF EXISTS TB_EOS_ACTION_EVID;
DROP TABLE IF EXISTS TB_EOS_ACTION_ST_HIST;
DROP TABLE IF EXISTS TB_EOS_ACTION_PLAN;
DROP TABLE IF EXISTS TB_EOS_RISK_SCORE;
DROP TABLE IF EXISTS TB_EOS_RISK_ASSESS;
DROP TABLE IF EXISTS TB_EOS_RESOURCE;
DROP TABLE IF EXISTS TB_EOS_PRODUCT_LFC;
DROP TABLE IF EXISTS TB_EOS_PRODUCT_VER;
DROP TABLE IF EXISTS TB_EOS_PRODUCT;
DROP TABLE IF EXISTS TB_EOS_POLICY;
DROP TABLE IF EXISTS TB_EOS_CODE;
DROP TABLE IF EXISTS TB_EOS_CODE_GRP;
DROP TABLE IF EXISTS TB_EOS_EVIDENCE;

-- ========== CODE ==========
CREATE TABLE TB_EOS_CODE_GRP (
    GRP_ID           VARCHAR(40)   NOT NULL,
    GRP_NAME         VARCHAR(120)  NOT NULL,
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50)   NOT NULL,
    REG_DTM          VARCHAR(17)   NOT NULL,
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_EOS_CODE_GRP_PK PRIMARY KEY (GRP_ID)
);

CREATE TABLE TB_EOS_CODE (
    GRP_ID           VARCHAR(40)   NOT NULL,
    CODE             VARCHAR(40)   NOT NULL,
    CODE_NAME        VARCHAR(120)  NOT NULL,
    SORT_ORD         INT           DEFAULT 0,
    USE_YN           CHAR(1)       NOT NULL DEFAULT 'Y',
    VALID_FROM_YMD   VARCHAR(8),
    VALID_TO_YMD     VARCHAR(8),
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50)   NOT NULL,
    REG_DTM          VARCHAR(17)   NOT NULL,
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_EOS_CODE_PK PRIMARY KEY (GRP_ID, CODE),
    CONSTRAINT TB_EOS_CODE_FK_GRP FOREIGN KEY (GRP_ID) REFERENCES TB_EOS_CODE_GRP (GRP_ID)
);

-- ========== EVIDENCE ==========
CREATE TABLE TB_EOS_EVIDENCE (
    EVIDENCE_ID      VARCHAR(40)   NOT NULL,
    FILE_NAME        VARCHAR(260)  NOT NULL,
    CONTENT_TYPE     VARCHAR(120),
    STORAGE_URI      VARCHAR(500)  NOT NULL,
    ACL_SCOPE_CD     VARCHAR(40)   NOT NULL,
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50)   NOT NULL,
    REG_DTM          VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_EVIDENCE_PK PRIMARY KEY (EVIDENCE_ID)
);

-- ========== POLICY ==========
CREATE TABLE TB_EOS_POLICY (
    POLICY_ID            VARCHAR(40)   NOT NULL,
    POLICY_TYPE_CD       VARCHAR(40)   NOT NULL,
    POLICY_KEY           VARCHAR(80)   NOT NULL,
    POLICY_VAL           VARCHAR(2000) NOT NULL,
    EFFECTIVE_FROM_DTM   VARCHAR(17)   NOT NULL,
    EFFECTIVE_TO_DTM     VARCHAR(17),
    USE_YN               CHAR(1)       NOT NULL DEFAULT 'Y',
    CHANGE_REASON        VARCHAR(500),
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_POLICY_PK PRIMARY KEY (POLICY_ID)
);

CREATE INDEX IX_EOS_POLICY_TYPE ON TB_EOS_POLICY (POLICY_TYPE_CD, EFFECTIVE_TO_DTM);

-- ========== PRODUCT ==========
CREATE TABLE TB_EOS_PRODUCT (
    PRODUCT_ID         VARCHAR(40)   NOT NULL,
    PRODUCT_NAME       VARCHAR(120)  NOT NULL,
    VENDOR_CD          VARCHAR(40),
    RESOURCE_TYPE_CD   VARCHAR(40)   NOT NULL,
    USE_YN             CHAR(1)       NOT NULL DEFAULT 'Y',
    REMARK             VARCHAR(500),
    REG_USER_ID        VARCHAR(50)   NOT NULL,
    REG_DTM            VARCHAR(17)   NOT NULL,
    CHG_USER_ID        VARCHAR(50),
    CHG_DTM            VARCHAR(17),
    CONSTRAINT TB_EOS_PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT TB_EOS_PRODUCT_UK1 UNIQUE (RESOURCE_TYPE_CD, PRODUCT_NAME)
);

CREATE TABLE TB_EOS_PRODUCT_VER (
    VERSION_ID       VARCHAR(40)   NOT NULL,
    PRODUCT_ID       VARCHAR(40)   NOT NULL,
    VERSION_NO       VARCHAR(80)   NOT NULL,
    USE_YN           CHAR(1)       NOT NULL DEFAULT 'Y',
    REMARK           VARCHAR(500),
    REG_USER_ID      VARCHAR(50)   NOT NULL,
    REG_DTM          VARCHAR(17)   NOT NULL,
    CHG_USER_ID      VARCHAR(50),
    CHG_DTM          VARCHAR(17),
    CONSTRAINT TB_EOS_PRODUCT_VER_PK PRIMARY KEY (VERSION_ID),
    CONSTRAINT TB_EOS_PRODUCT_VER_UK1 UNIQUE (PRODUCT_ID, VERSION_NO),
    CONSTRAINT TB_EOS_PRODUCT_VER_FK_PRD FOREIGN KEY (PRODUCT_ID) REFERENCES TB_EOS_PRODUCT (PRODUCT_ID)
);

CREATE TABLE TB_EOS_PRODUCT_LFC (
    LFC_ID               VARCHAR(40)   NOT NULL,
    VERSION_ID           VARCHAR(40)   NOT NULL,
    GA_YMD               VARCHAR(8),
    EOS_YMD              VARCHAR(8),
    EOL_YMD              VARCHAR(8),
    EVIDENCE_ID          VARCHAR(40),
    SOURCE_DESC          VARCHAR(500),
    EFFECTIVE_FROM_DTM   VARCHAR(17)   NOT NULL,
    EFFECTIVE_TO_DTM     VARCHAR(17),
    CHANGE_REASON        VARCHAR(500)  NOT NULL,
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_PRODUCT_LFC_PK PRIMARY KEY (LFC_ID),
    CONSTRAINT TB_EOS_PRODUCT_LFC_FK_VER FOREIGN KEY (VERSION_ID) REFERENCES TB_EOS_PRODUCT_VER (VERSION_ID),
    CONSTRAINT TB_EOS_PRODUCT_LFC_FK_EVD FOREIGN KEY (EVIDENCE_ID) REFERENCES TB_EOS_EVIDENCE (EVIDENCE_ID)
);

CREATE INDEX IX_EOS_LFC_VER ON TB_EOS_PRODUCT_LFC (VERSION_ID, EFFECTIVE_TO_DTM);

-- ========== RESOURCE ==========
CREATE TABLE TB_EOS_RESOURCE (
    RESOURCE_ID            VARCHAR(40)   NOT NULL,
    RESOURCE_NAME          VARCHAR(120)  NOT NULL,
    VERSION_ID             VARCHAR(40)   NOT NULL,
    ENV_CD                 VARCHAR(40)   NOT NULL,
    CENTER_CD              VARCHAR(40),
    HOST_NAME              VARCHAR(120),
    IP_ADDR                VARCHAR(64),
    NSIGHT_AREA_CD         VARCHAR(40),
    ORG_CD                 VARCHAR(40),
    OWNER_USER_ID          VARCHAR(50),
    EOS_STATUS_CD          VARCHAR(40)   NOT NULL,
    RISK_GRADE_CD          VARCHAR(40),
    EXCEPTION_ACTIVE_YN    CHAR(1)       NOT NULL DEFAULT 'N',
    USE_YN                 CHAR(1)       NOT NULL DEFAULT 'Y',
    DISPOSE_YN             CHAR(1)       NOT NULL DEFAULT 'N',
    REMARK                 VARCHAR(500),
    REG_USER_ID            VARCHAR(50)   NOT NULL,
    REG_DTM                VARCHAR(17)   NOT NULL,
    CHG_USER_ID            VARCHAR(50),
    CHG_DTM                VARCHAR(17),
    CONSTRAINT TB_EOS_RESOURCE_PK PRIMARY KEY (RESOURCE_ID),
    CONSTRAINT TB_EOS_RESOURCE_FK_VER FOREIGN KEY (VERSION_ID) REFERENCES TB_EOS_PRODUCT_VER (VERSION_ID)
);

CREATE INDEX IX_EOS_RSC_STATUS ON TB_EOS_RESOURCE (EOS_STATUS_CD, DISPOSE_YN);
CREATE INDEX IX_EOS_RSC_RISK ON TB_EOS_RESOURCE (RISK_GRADE_CD, DISPOSE_YN);
CREATE INDEX IX_EOS_RSC_ORG ON TB_EOS_RESOURCE (ORG_CD);
CREATE INDEX IX_EOS_RSC_VER ON TB_EOS_RESOURCE (VERSION_ID);

-- ========== RISK ==========
CREATE TABLE TB_EOS_RISK_ASSESS (
    ASSESS_ID        VARCHAR(40)   NOT NULL,
    RESOURCE_ID      VARCHAR(40)   NOT NULL,
    TOTAL_SCORE     INT           NOT NULL,
    RISK_GRADE_CD    VARCHAR(40)   NOT NULL,
    COMMENT_TXT      VARCHAR(2000),
    ASSESSOR_ID      VARCHAR(50)   NOT NULL,
    ASSESS_DTM       VARCHAR(17)   NOT NULL,
    POLICY_ID        VARCHAR(40),
    REG_USER_ID      VARCHAR(50)   NOT NULL,
    REG_DTM          VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_RISK_ASSESS_PK PRIMARY KEY (ASSESS_ID),
    CONSTRAINT TB_EOS_RISK_ASSESS_FK_RSC FOREIGN KEY (RESOURCE_ID) REFERENCES TB_EOS_RESOURCE (RESOURCE_ID)
);

CREATE INDEX IX_EOS_RISK_RSC ON TB_EOS_RISK_ASSESS (RESOURCE_ID, ASSESS_DTM);

CREATE TABLE TB_EOS_RISK_SCORE (
    ASSESS_ID        VARCHAR(40)   NOT NULL,
    ITEM_CD          VARCHAR(20)   NOT NULL,
    SCORE            INT           NOT NULL,
    CONSTRAINT TB_EOS_RISK_SCORE_PK PRIMARY KEY (ASSESS_ID, ITEM_CD),
    CONSTRAINT TB_EOS_RISK_SCORE_FK_ASS FOREIGN KEY (ASSESS_ID) REFERENCES TB_EOS_RISK_ASSESS (ASSESS_ID),
    CONSTRAINT TB_EOS_RISK_SCORE_CK_SC CHECK (SCORE >= 1 AND SCORE <= 5)
);

-- ========== ACTION ==========
CREATE TABLE TB_EOS_ACTION_PLAN (
    ACTION_ID            VARCHAR(40)   NOT NULL,
    RESOURCE_ID          VARCHAR(40)   NOT NULL,
    ACTION_TYPE_CD       VARCHAR(40)   NOT NULL,
    CUR_VERSION_ID       VARCHAR(40),
    TGT_VERSION_ID       VARCHAR(40),
    DETAIL_TXT           VARCHAR(2000) NOT NULL,
    IMPACT_TXT           VARCHAR(2000) NOT NULL,
    PREREQ_TXT           VARCHAR(2000),
    TEST_PLAN_TXT        VARCHAR(2000) NOT NULL,
    CUTOVER_TYPE_CD      VARCHAR(40)   NOT NULL,
    OUTAGE_YN            CHAR(1)       NOT NULL DEFAULT 'N',
    OFFHOURS_YN          CHAR(1)       DEFAULT 'N',
    DR_VERIFY_YN         CHAR(1)       DEFAULT 'N',
    ROLLBACK_COND_TXT    VARCHAR(2000) NOT NULL,
    ROLLBACK_PROC_TXT    VARCHAR(2000) NOT NULL,
    ROLLBACK_TARGET_TXT  VARCHAR(2000) NOT NULL,
    ORG_CD               VARCHAR(40)   NOT NULL,
    OWNER_USER_ID        VARCHAR(50)   NOT NULL,
    PLAN_START_YMD       VARCHAR(8)    NOT NULL,
    PLAN_END_YMD         VARCHAR(8)    NOT NULL,
    ACTUAL_END_YMD       VARCHAR(8),
    STATUS_CD            VARCHAR(40)   NOT NULL,
    ISSUE_TXT            VARCHAR(2000),
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CHG_USER_ID          VARCHAR(50),
    CHG_DTM              VARCHAR(17),
    CONSTRAINT TB_EOS_ACTION_PLAN_PK PRIMARY KEY (ACTION_ID),
    CONSTRAINT TB_EOS_ACTION_PLAN_FK_RSC FOREIGN KEY (RESOURCE_ID) REFERENCES TB_EOS_RESOURCE (RESOURCE_ID)
);

CREATE INDEX IX_EOS_ACT_RSC ON TB_EOS_ACTION_PLAN (RESOURCE_ID, STATUS_CD);

CREATE TABLE TB_EOS_ACTION_ST_HIST (
    HIST_ID          VARCHAR(40)   NOT NULL,
    ACTION_ID        VARCHAR(40)   NOT NULL,
    FROM_STATUS_CD   VARCHAR(40),
    TO_STATUS_CD     VARCHAR(40)   NOT NULL,
    CHG_USER_ID      VARCHAR(50)   NOT NULL,
    CHG_DTM          VARCHAR(17)   NOT NULL,
    REASON_TXT       VARCHAR(500),
    CONSTRAINT TB_EOS_ACTION_ST_HIST_PK PRIMARY KEY (HIST_ID),
    CONSTRAINT TB_EOS_ACTION_ST_HIST_FK FOREIGN KEY (ACTION_ID) REFERENCES TB_EOS_ACTION_PLAN (ACTION_ID)
);

CREATE TABLE TB_EOS_ACTION_EVID (
    ACTION_ID        VARCHAR(40)   NOT NULL,
    EVIDENCE_ID      VARCHAR(40)   NOT NULL,
    VERIFY_USER_ID   VARCHAR(50),
    VERIFY_DTM       VARCHAR(17),
    VERIFY_RESULT_CD VARCHAR(40),
    CONSTRAINT TB_EOS_ACTION_EVID_PK PRIMARY KEY (ACTION_ID, EVIDENCE_ID),
    CONSTRAINT TB_EOS_ACTION_EVID_FK_ACT FOREIGN KEY (ACTION_ID) REFERENCES TB_EOS_ACTION_PLAN (ACTION_ID),
    CONSTRAINT TB_EOS_ACTION_EVID_FK_EVD FOREIGN KEY (EVIDENCE_ID) REFERENCES TB_EOS_EVIDENCE (EVIDENCE_ID)
);

-- ========== EXCEPTION ==========
CREATE TABLE TB_EOS_EXC_REQ (
    EXC_REQ_ID           VARCHAR(40)   NOT NULL,
    RESOURCE_ID          VARCHAR(40)   NOT NULL,
    REQ_ORG_CD           VARCHAR(40)   NOT NULL,
    REQ_USER_ID          VARCHAR(50)   NOT NULL,
    REQ_DTM              VARCHAR(17)   NOT NULL,
    START_YMD            VARCHAR(8)    NOT NULL,
    END_YMD              VARCHAR(8)    NOT NULL,
    REASON_TXT           VARCHAR(2000) NOT NULL,
    BLOCKER_TXT          VARCHAR(2000) NOT NULL,
    MITIGATION_TXT       VARCHAR(2000) NOT NULL,
    FINAL_PLAN_TXT       VARCHAR(2000) NOT NULL,
    FINAL_TARGET_YMD     VARCHAR(8)    NOT NULL,
    MONTHLY_CHECK_YN     CHAR(1)       NOT NULL DEFAULT 'Y',
    EXIT_CRITERIA_TXT    VARCHAR(2000) NOT NULL,
    STATUS_CD            VARCHAR(40)   NOT NULL,
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CHG_USER_ID          VARCHAR(50),
    CHG_DTM              VARCHAR(17),
    CONSTRAINT TB_EOS_EXC_REQ_PK PRIMARY KEY (EXC_REQ_ID),
    CONSTRAINT TB_EOS_EXC_REQ_FK_RSC FOREIGN KEY (RESOURCE_ID) REFERENCES TB_EOS_RESOURCE (RESOURCE_ID)
);

CREATE INDEX IX_EOS_EXC_REQ_ST ON TB_EOS_EXC_REQ (STATUS_CD, REQ_DTM);

CREATE TABLE TB_EOS_EXC_APPR (
    APPR_ID              VARCHAR(40)   NOT NULL,
    EXC_REQ_ID           VARCHAR(40)   NOT NULL,
    DECISION_CD          VARCHAR(40)   NOT NULL,
    CONDITION_TXT        VARCHAR(2000),
    REJECT_REASON_TXT    VARCHAR(2000),
    APPROVER_ID          VARCHAR(50)   NOT NULL,
    APPROVE_DTM          VARCHAR(17)   NOT NULL,
    EXTEND_OF_APPR_ID    VARCHAR(40),
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_EXC_APPR_PK PRIMARY KEY (APPR_ID),
    CONSTRAINT TB_EOS_EXC_APPR_FK_REQ FOREIGN KEY (EXC_REQ_ID) REFERENCES TB_EOS_EXC_REQ (EXC_REQ_ID),
    CONSTRAINT TB_EOS_EXC_APPR_FK_EXT FOREIGN KEY (EXTEND_OF_APPR_ID) REFERENCES TB_EOS_EXC_APPR (APPR_ID)
);

CREATE TABLE TB_EOS_MONTHLY_CHK (
    CHECK_ID             VARCHAR(40)   NOT NULL,
    EXC_REQ_ID           VARCHAR(40)   NOT NULL,
    CHECK_YM             VARCHAR(6)    NOT NULL,
    MITIGATION_OK_YN     CHAR(1)       NOT NULL,
    RESIDUAL_RISK_TXT    VARCHAR(2000),
    PLAN_PROGRESS_TXT    VARCHAR(2000),
    ISSUE_TXT            VARCHAR(2000),
    NEXT_CHECK_YMD       VARCHAR(8),
    CHECKER_ID           VARCHAR(50)   NOT NULL,
    CHECK_DTM            VARCHAR(17)   NOT NULL,
    REG_USER_ID          VARCHAR(50)   NOT NULL,
    REG_DTM              VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_MONTHLY_CHK_PK PRIMARY KEY (CHECK_ID),
    CONSTRAINT TB_EOS_MONTHLY_CHK_UK1 UNIQUE (EXC_REQ_ID, CHECK_YM),
    CONSTRAINT TB_EOS_MONTHLY_CHK_FK_REQ FOREIGN KEY (EXC_REQ_ID) REFERENCES TB_EOS_EXC_REQ (EXC_REQ_ID)
);

-- ========== AUDIT ==========
CREATE TABLE TB_EOS_CHG_HIST (
    HIST_ID          VARCHAR(40)   NOT NULL,
    TRACE_ID         VARCHAR(64)   NOT NULL,
    USER_ID          VARCHAR(50)   NOT NULL,
    ORG_CD           VARCHAR(40),
    SERVICE_ID       VARCHAR(100)  NOT NULL,
    ENTITY_TYPE      VARCHAR(40)   NOT NULL,
    ENTITY_ID        VARCHAR(40)   NOT NULL,
    ACTION_CD        VARCHAR(40)   NOT NULL,
    BEFORE_JSON      CLOB,
    AFTER_JSON       CLOB,
    RESULT_CD        VARCHAR(20)   NOT NULL,
    REASON_TXT       VARCHAR(500),
    EVENT_DTM        VARCHAR(17)   NOT NULL,
    CONSTRAINT TB_EOS_CHG_HIST_PK PRIMARY KEY (HIST_ID)
);

CREATE INDEX IX_EOS_CHG_ENT ON TB_EOS_CHG_HIST (ENTITY_TYPE, ENTITY_ID, EVENT_DTM);
CREATE INDEX IX_EOS_CHG_TRACE ON TB_EOS_CHG_HIST (TRACE_ID);
CREATE INDEX IX_EOS_CHG_USER ON TB_EOS_CHG_HIST (USER_ID, EVENT_DTM);

CREATE TABLE TB_EOS_BATCH_RUN (
    RUN_ID          VARCHAR(40)   NOT NULL,
    JOB_ID          VARCHAR(80)   NOT NULL,
    START_DTM       VARCHAR(17)   NOT NULL,
    END_DTM         VARCHAR(17),
    PROCESS_CNT     INT           NOT NULL DEFAULT 0,
    SUCCESS_CNT     INT           NOT NULL DEFAULT 0,
    FAIL_CNT        INT           NOT NULL DEFAULT 0,
    STATUS_CD       VARCHAR(20)   NOT NULL,
    MSG_TXT         VARCHAR(500),
    CONSTRAINT TB_EOS_BATCH_RUN_PK PRIMARY KEY (RUN_ID)
);

CREATE INDEX IX_EOS_BATCH_JOB ON TB_EOS_BATCH_RUN (JOB_ID, START_DTM);
