CREATE TABLE IF NOT EXISTS UD_FILE (
    FILE_ID VARCHAR(64) NOT NULL,
    ORIGINAL_NAME VARCHAR(500) NOT NULL,
    STORED_PATH VARCHAR(1000) NOT NULL,
    CONTENT_TYPE VARCHAR(200),
    FILE_SIZE BIGINT NOT NULL,
    UPLOAD_USER VARCHAR(100),
    UPLOAD_TIME VARCHAR(14) NOT NULL,
    BUSINESS_CODE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PRIMARY KEY (FILE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_UD_FILE_BIZ ON UD_FILE (BUSINESS_CODE, UPLOAD_TIME DESC);

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);
