CREATE TABLE IF NOT EXISTS NSIGHT_UPLOAD_FILE (
    FILE_ID VARCHAR(64) PRIMARY KEY,
    ORIGINAL_FILENAME VARCHAR(500),
    STORED_PATH VARCHAR(1000),
    FILE_SIZE BIGINT,
    CONTENT_TYPE VARCHAR(200),
    CREATED_AT TIMESTAMP
);
