# ztomcat(8080) WAR 공통 — tcf-web.jar (local,tomcat 프로파일)
logging:
  charset:
    file: UTF-8
  file:
    name: ${CATALINA_BASE:./logs}/logs/nsight-${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 14
