CREATE TABLE IF NOT EXISTS AV_SAMPLE (
    SAMPLE_KEY   VARCHAR(30) PRIMARY KEY,
    SAMPLE_NAME  VARCHAR(100) NOT NULL,
    USE_YN       CHAR(1) DEFAULT 'Y',
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 조회 검증용 시드 데이터
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-001', 'AV 샘플 첫번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-002', 'AV 샘플 두번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-003', 'AV 샘플 세번째', 'N');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-004', 'AV 샘플 네번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-005', 'AV 샘플 다섯번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-006', 'AV 샘플 여섯번째', 'Y');
