CREATE TABLE IF NOT EXISTS AV_SAMPLE (
    SAMPLE_KEY   VARCHAR(30) PRIMARY KEY,
    SAMPLE_NAME  VARCHAR(100) NOT NULL,
    USE_YN       CHAR(1) DEFAULT 'Y',
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 조회 검증용 시드 데이터
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-001', 'AV 샘플 첫번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-002', 'AV 샘플 두번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-003', 'AV 샘플 세번째', 'N');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-004', 'AV 샘플 네번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-005', 'AV 샘플 다섯번째', 'Y');
MERGE INTO AV_SAMPLE (SAMPLE_KEY, SAMPLE_NAME, USE_YN) KEY (SAMPLE_KEY) VALUES ('AV-006', 'AV 샘플 여섯번째', 'Y');

-- AV 고객연락처 (C04 확정: 신규 테이블 · PK CONTACT_ID). 운영 SoT 아님, AA 승인 전 운영 DB 반영 금지.
CREATE TABLE IF NOT EXISTS AV_CUSTOMER_CONTACT (
    CONTACT_ID     VARCHAR(30) PRIMARY KEY,
    CUSTOMER_NO    VARCHAR(20) NOT NULL,
    CONTACT_TYPE   VARCHAR(20) NOT NULL,
    CONTACT_VALUE  VARCHAR(200) NOT NULL,
    USE_YN         CHAR(1) DEFAULT 'Y',
    REG_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DTM        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_AV_CCT_CUST
    ON AV_CUSTOMER_CONTACT (CUSTOMER_NO, USE_YN, CONTACT_TYPE);

MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-001', 'C0001', 'MOBILE', '010-1111-2222', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-002', 'C0001', 'EMAIL', 'c0001@example.com', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-003', 'C0001', 'MOBILE', '010-9999-8888', 'N');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-004', 'C0002', 'MOBILE', '010-3333-4444', 'Y');
MERGE INTO AV_CUSTOMER_CONTACT (CONTACT_ID, CUSTOMER_NO, CONTACT_TYPE, CONTACT_VALUE, USE_YN)
    KEY (CONTACT_ID) VALUES ('ACT-005', 'C0002', 'HOME', '02-123-4567', 'Y');

-- AV 자산평가 (REQ-AV-001 / PILOT-AV-001 / DA 승인: AssetValuation). 운영 DDL 직접 실행 금지.
-- 로컬 스키마 교체: SAMPLE 컬럼 → Pilot 계약 (BRANCH_ID, BASE_DATE, DELETE_YN).
DROP TABLE IF EXISTS AV_ASSET_VALUATION;
DROP TABLE IF EXISTS AV_ASSET_MASTER;
DROP TABLE IF EXISTS CM_CODE_DETAIL;

CREATE TABLE AV_ASSET_MASTER (
    ASSET_ID    VARCHAR(32) PRIMARY KEY,
    ASSET_NAME  VARCHAR(100) NOT NULL,
    USE_YN      CHAR(1) DEFAULT 'Y'
);

CREATE TABLE CM_CODE_DETAIL (
    CODE_GROUP  VARCHAR(32) NOT NULL,
    CODE_VALUE  VARCHAR(32) NOT NULL,
    CODE_NAME   VARCHAR(100) NOT NULL,
    USE_YN      CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (CODE_GROUP, CODE_VALUE)
);

CREATE TABLE AV_ASSET_VALUATION (
    VALUATION_ID            VARCHAR(32) PRIMARY KEY,
    ASSET_ID                VARCHAR(32) NOT NULL,
    BRANCH_ID               VARCHAR(20) NOT NULL,
    BASE_DATE               VARCHAR(8) NOT NULL,
    CUSTOMER_NO             VARCHAR(20) NOT NULL,
    ASSET_TYPE_CODE         VARCHAR(32) NOT NULL,
    VALUATION_STATUS_CODE   VARCHAR(32) NOT NULL,
    VALUATION_AMT           DECIMAL(18, 2),
    VALUATION_DATE          VARCHAR(8),
    DELETE_YN               CHAR(1) DEFAULT 'N',
    REG_DTM                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DTM                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_AV_AVL_BRANCH_BASE
    ON AV_ASSET_VALUATION (BRANCH_ID, BASE_DATE, DELETE_YN);

MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('ASSET_TYPE', 'REAL_ESTATE', '부동산', 'Y');
MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('ASSET_TYPE', 'MOVABLE', '동산', 'Y');
MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('ASSET_TYPE', 'SECURITIES', '유가증권', 'Y');
MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('VALUATION_STATUS', 'COMPLETED', '평가완료', 'Y');
MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('VALUATION_STATUS', 'IN_PROGRESS', '평가진행', 'Y');
MERGE INTO CM_CODE_DETAIL (CODE_GROUP, CODE_VALUE, CODE_NAME, USE_YN)
    KEY (CODE_GROUP, CODE_VALUE) VALUES ('VALUATION_STATUS', 'CANCELLED', '평가취소', 'Y');

MERGE INTO AV_ASSET_MASTER (ASSET_ID, ASSET_NAME, USE_YN)
    KEY (ASSET_ID) VALUES ('AST-000001', '강남 오피스', 'Y');
MERGE INTO AV_ASSET_MASTER (ASSET_ID, ASSET_NAME, USE_YN)
    KEY (ASSET_ID) VALUES ('AST-000002', '설비 A', 'Y');
MERGE INTO AV_ASSET_MASTER (ASSET_ID, ASSET_NAME, USE_YN)
    KEY (ASSET_ID) VALUES ('AST-000003', '주식 포트폴리오', 'Y');

MERGE INTO AV_ASSET_VALUATION
    (VALUATION_ID, ASSET_ID, BRANCH_ID, BASE_DATE, CUSTOMER_NO, ASSET_TYPE_CODE,
     VALUATION_STATUS_CODE, VALUATION_AMT, VALUATION_DATE, DELETE_YN)
    KEY (VALUATION_ID) VALUES
    ('AVL-001', 'AST-000001', 'BR001', '20260805', '1234567890', 'REAL_ESTATE',
     'COMPLETED', 350000000.00, '20260805', 'N');
MERGE INTO AV_ASSET_VALUATION
    (VALUATION_ID, ASSET_ID, BRANCH_ID, BASE_DATE, CUSTOMER_NO, ASSET_TYPE_CODE,
     VALUATION_STATUS_CODE, VALUATION_AMT, VALUATION_DATE, DELETE_YN)
    KEY (VALUATION_ID) VALUES
    ('AVL-002', 'AST-000002', 'BR001', '20260805', '1234567890', 'MOVABLE',
     'IN_PROGRESS', 12000000.00, '20260804', 'N');
MERGE INTO AV_ASSET_VALUATION
    (VALUATION_ID, ASSET_ID, BRANCH_ID, BASE_DATE, CUSTOMER_NO, ASSET_TYPE_CODE,
     VALUATION_STATUS_CODE, VALUATION_AMT, VALUATION_DATE, DELETE_YN)
    KEY (VALUATION_ID) VALUES
    ('AVL-003', 'AST-000003', 'BR001', '20260805', '9999888877', 'SECURITIES',
     'COMPLETED', 5000000.00, '20260803', 'N');
MERGE INTO AV_ASSET_VALUATION
    (VALUATION_ID, ASSET_ID, BRANCH_ID, BASE_DATE, CUSTOMER_NO, ASSET_TYPE_CODE,
     VALUATION_STATUS_CODE, VALUATION_AMT, VALUATION_DATE, DELETE_YN)
    KEY (VALUATION_ID) VALUES
    ('AVL-004', 'AST-000001', 'BR002', '20260805', '1111222233', 'REAL_ESTATE',
     'COMPLETED', 999000000.00, '20260805', 'N');
MERGE INTO AV_ASSET_VALUATION
    (VALUATION_ID, ASSET_ID, BRANCH_ID, BASE_DATE, CUSTOMER_NO, ASSET_TYPE_CODE,
     VALUATION_STATUS_CODE, VALUATION_AMT, VALUATION_DATE, DELETE_YN)
    KEY (VALUATION_ID) VALUES
    ('AVL-005', 'AST-000002', 'BR001', '20260805', '1234567890', 'MOVABLE',
     'CANCELLED', 100.00, '20260801', 'Y');
