-- NSIGHT AUTO HARNESS - CORE TABLES / Oracle 19c+

CREATE TABLE HAR_PROJECT (
 PROJECT_ID VARCHAR2(40) NOT NULL, PROJECT_NAME VARCHAR2(200) NOT NULL,
 DESCRIPTION VARCHAR2(2000), BASE_PACKAGE VARCHAR2(300) DEFAULT 'com.nh.nsight.harness' NOT NULL,
 STATUS_CODE VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL, OWNER_ORG_CODE VARCHAR2(50),
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_PROJECT PRIMARY KEY (PROJECT_ID),
 CONSTRAINT CK_HAR_PROJECT_STATUS CHECK (STATUS_CODE IN ('ACTIVE','SUSPENDED','RETIRED'))
);

CREATE TABLE HAR_BASELINE (
 BASELINE_ID VARCHAR2(50) NOT NULL, PROJECT_ID VARCHAR2(40) NOT NULL, BASELINE_NAME VARCHAR2(200) NOT NULL,
 GIT_REPOSITORY VARCHAR2(500), GIT_BRANCH VARCHAR2(200), GIT_COMMIT_SHA VARCHAR2(64),
 DOCUMENT_HASH VARCHAR2(80), RULESET_VERSION VARCHAR2(50), PROMPT_VERSION VARCHAR2(50), TOOLSET_VERSION VARCHAR2(50),
 STATUS_CODE VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL, BASELINED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_BASELINE PRIMARY KEY (BASELINE_ID),
 CONSTRAINT FK_HAR_BASELINE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES HAR_PROJECT(PROJECT_ID),
 CONSTRAINT CK_HAR_BASELINE_STATUS CHECK (STATUS_CODE IN ('DRAFT','BASELINED','SUPERSEDED','RETIRED'))
);

CREATE TABLE HAR_WORKFLOW_DEF (
 WORKFLOW_ID VARCHAR2(80) NOT NULL, WORKFLOW_VERSION VARCHAR2(30) NOT NULL,
 WORKFLOW_NAME VARCHAR2(200) NOT NULL, WORKFLOW_TYPE VARCHAR2(50) NOT NULL,
 YAML_URI VARCHAR2(1000) NOT NULL, CONTENT_HASH VARCHAR2(80) NOT NULL,
 STATUS_CODE VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
 EFFECTIVE_FROM TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, EFFECTIVE_TO TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_WORKFLOW_DEF PRIMARY KEY (WORKFLOW_ID, WORKFLOW_VERSION),
 CONSTRAINT CK_HAR_WF_STATUS CHECK (STATUS_CODE IN ('DRAFT','ACTIVE','DEPRECATED','RETIRED'))
);

CREATE TABLE HAR_RUN (
 RUN_ID VARCHAR2(50) NOT NULL, PROJECT_ID VARCHAR2(40) NOT NULL, BASELINE_ID VARCHAR2(50),
 WORKFLOW_ID VARCHAR2(80) NOT NULL, WORKFLOW_VERSION VARCHAR2(30) NOT NULL,
 RUN_NAME VARCHAR2(200), RUN_TYPE VARCHAR2(50) NOT NULL, STATUS_CODE VARCHAR2(40) NOT NULL,
 CURRENT_STAGE_ID VARCHAR2(80), REQUESTED_BY VARCHAR2(100) NOT NULL,
 PRIORITY_CODE VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
 INPUT_MANIFEST_ID VARCHAR2(80), FINAL_MANIFEST_ID VARCHAR2(80), FAILURE_CODE VARCHAR2(80), FAILURE_MESSAGE VARCHAR2(2000),
 STARTED_AT TIMESTAMP(6) WITH TIME ZONE, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_RUN PRIMARY KEY (RUN_ID),
 CONSTRAINT FK_HAR_RUN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES HAR_PROJECT(PROJECT_ID),
 CONSTRAINT FK_HAR_RUN_BASELINE FOREIGN KEY (BASELINE_ID) REFERENCES HAR_BASELINE(BASELINE_ID),
 CONSTRAINT FK_HAR_RUN_WF FOREIGN KEY (WORKFLOW_ID, WORKFLOW_VERSION) REFERENCES HAR_WORKFLOW_DEF(WORKFLOW_ID, WORKFLOW_VERSION),
 CONSTRAINT CK_HAR_RUN_PRIORITY CHECK (PRIORITY_CODE IN ('LOW','NORMAL','HIGH','CRITICAL'))
);

CREATE TABLE HAR_RUN_STAGE (
 RUN_STAGE_ID VARCHAR2(70) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL,
 STAGE_ID VARCHAR2(80) NOT NULL, STAGE_NAME VARCHAR2(200) NOT NULL, STAGE_ORDER NUMBER(5) NOT NULL,
 STATUS_CODE VARCHAR2(40) NOT NULL, GATE_ID VARCHAR2(40),
 STARTED_AT TIMESTAMP(6) WITH TIME ZONE, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_RUN_STAGE PRIMARY KEY (RUN_STAGE_ID),
 CONSTRAINT FK_HAR_STAGE_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT UK_HAR_STAGE_RUN UNIQUE (RUN_ID, STAGE_ID)
);

CREATE TABLE HAR_RUN_STEP (
 RUN_STEP_ID VARCHAR2(80) NOT NULL, RUN_STAGE_ID VARCHAR2(70) NOT NULL,
 STEP_ID VARCHAR2(100) NOT NULL, STEP_NAME VARCHAR2(200) NOT NULL, STEP_ORDER NUMBER(5) NOT NULL,
 AGENT_ID VARCHAR2(100), CONTRACT_ID VARCHAR2(100), STATUS_CODE VARCHAR2(40) NOT NULL,
 TIMEOUT_SECONDS NUMBER(10), MAX_ATTEMPTS NUMBER(5) DEFAULT 1 NOT NULL,
 STARTED_AT TIMESTAMP(6) WITH TIME ZONE, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_RUN_STEP PRIMARY KEY (RUN_STEP_ID),
 CONSTRAINT FK_HAR_STEP_STAGE FOREIGN KEY (RUN_STAGE_ID) REFERENCES HAR_RUN_STAGE(RUN_STAGE_ID),
 CONSTRAINT UK_HAR_STEP_STAGE UNIQUE (RUN_STAGE_ID, STEP_ID)
);

CREATE TABLE HAR_AGENT_TASK (
 TASK_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, RUN_STEP_ID VARCHAR2(80) NOT NULL,
 AGENT_ID VARCHAR2(100) NOT NULL, CONTRACT_ID VARCHAR2(100) NOT NULL, CONTRACT_VERSION VARCHAR2(30) NOT NULL,
 IDEMPOTENCY_KEY VARCHAR2(300) NOT NULL, STATUS_CODE VARCHAR2(40) NOT NULL,
 INPUT_MANIFEST_ID VARCHAR2(80), OUTPUT_MANIFEST_ID VARCHAR2(80), CURRENT_ATTEMPT_NO NUMBER(5) DEFAULT 0 NOT NULL,
 LEASE_OWNER VARCHAR2(200), LEASE_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE, READY_AT TIMESTAMP(6) WITH TIME ZONE,
 STARTED_AT TIMESTAMP(6) WITH TIME ZONE, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_AGENT_TASK PRIMARY KEY (TASK_ID),
 CONSTRAINT FK_HAR_TASK_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_TASK_STEP FOREIGN KEY (RUN_STEP_ID) REFERENCES HAR_RUN_STEP(RUN_STEP_ID),
 CONSTRAINT UK_HAR_TASK_IDEMP UNIQUE (IDEMPOTENCY_KEY)
);

CREATE TABLE HAR_TASK_ATTEMPT (
 TASK_ATTEMPT_ID VARCHAR2(90) NOT NULL, TASK_ID VARCHAR2(80) NOT NULL, ATTEMPT_NO NUMBER(5) NOT NULL,
 WORKER_ID VARCHAR2(200), STATUS_CODE VARCHAR2(40) NOT NULL, EXIT_TYPE VARCHAR2(40), EXIT_CODE NUMBER(10),
 ERROR_CODE VARCHAR2(100), ERROR_MESSAGE VARCHAR2(4000), INPUT_TOKEN_COUNT NUMBER(19), OUTPUT_TOKEN_COUNT NUMBER(19),
 DURATION_MS NUMBER(19), STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_TASK_ATTEMPT PRIMARY KEY (TASK_ATTEMPT_ID),
 CONSTRAINT FK_HAR_ATTEMPT_TASK FOREIGN KEY (TASK_ID) REFERENCES HAR_AGENT_TASK(TASK_ID),
 CONSTRAINT UK_HAR_ATTEMPT_NO UNIQUE (TASK_ID, ATTEMPT_NO)
);

CREATE TABLE HAR_CHECKPOINT (
 CHECKPOINT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, RUN_STAGE_ID VARCHAR2(70),
 STATE_VERSION NUMBER(19) NOT NULL, BASELINE_HASH VARCHAR2(80), MANIFEST_HASH VARCHAR2(80) NOT NULL,
 CHECKPOINT_URI VARCHAR2(1000) NOT NULL, STATUS_CODE VARCHAR2(30) DEFAULT 'VALID' NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_CHECKPOINT PRIMARY KEY (CHECKPOINT_ID),
 CONSTRAINT FK_HAR_CP_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_CP_STAGE FOREIGN KEY (RUN_STAGE_ID) REFERENCES HAR_RUN_STAGE(RUN_STAGE_ID),
 CONSTRAINT CK_HAR_CP_STATUS CHECK (STATUS_CODE IN ('VALID','SUPERSEDED','INVALID'))
);

CREATE TABLE HAR_RESOURCE_LOCK (
 LOCK_ID VARCHAR2(80) NOT NULL, RESOURCE_TYPE VARCHAR2(40) NOT NULL, RESOURCE_ID VARCHAR2(500) NOT NULL,
 LOCK_MODE VARCHAR2(20) NOT NULL, OWNER_RUN_ID VARCHAR2(50) NOT NULL, OWNER_TASK_ID VARCHAR2(80),
 LEASE_TOKEN VARCHAR2(200) NOT NULL, ACQUIRED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, RELEASED_AT TIMESTAMP(6) WITH TIME ZONE,
 CONSTRAINT PK_HAR_RESOURCE_LOCK PRIMARY KEY (LOCK_ID),
 CONSTRAINT FK_HAR_LOCK_RUN FOREIGN KEY (OWNER_RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_LOCK_TASK FOREIGN KEY (OWNER_TASK_ID) REFERENCES HAR_AGENT_TASK(TASK_ID),
 CONSTRAINT CK_HAR_LOCK_MODE CHECK (LOCK_MODE IN ('READ','WRITE','EXCLUSIVE'))
);

CREATE TABLE HAR_ARTIFACT (
 ARTIFACT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, ARTIFACT_TYPE VARCHAR2(80) NOT NULL,
 LOGICAL_NAME VARCHAR2(500) NOT NULL, STATUS_CODE VARCHAR2(30) NOT NULL, CURRENT_VERSION_ID VARCHAR2(90),
 SOURCE_TASK_ID VARCHAR2(80), CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_ARTIFACT PRIMARY KEY (ARTIFACT_ID),
 CONSTRAINT FK_HAR_ART_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_ART_TASK FOREIGN KEY (SOURCE_TASK_ID) REFERENCES HAR_AGENT_TASK(TASK_ID)
);

CREATE TABLE HAR_ARTIFACT_VER (
 ARTIFACT_VERSION_ID VARCHAR2(90) NOT NULL, ARTIFACT_ID VARCHAR2(80) NOT NULL, VERSION_SEQ NUMBER(10) NOT NULL,
 ARTIFACT_URI VARCHAR2(1000) NOT NULL, CONTENT_HASH VARCHAR2(80) NOT NULL, CONTENT_SIZE NUMBER(19),
 MEDIA_TYPE VARCHAR2(200), SCHEMA_ID VARCHAR2(200), SCHEMA_VERSION VARCHAR2(30),
 IMMUTABLE_YN CHAR(1) DEFAULT 'N' NOT NULL, CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_ARTIFACT_VER PRIMARY KEY (ARTIFACT_VERSION_ID),
 CONSTRAINT FK_HAR_ART_VER FOREIGN KEY (ARTIFACT_ID) REFERENCES HAR_ARTIFACT(ARTIFACT_ID),
 CONSTRAINT UK_HAR_ART_VER UNIQUE (ARTIFACT_ID, VERSION_SEQ),
 CONSTRAINT CK_HAR_ART_IMMUTABLE CHECK (IMMUTABLE_YN IN ('Y','N'))
);
ALTER TABLE HAR_ARTIFACT ADD CONSTRAINT FK_HAR_ART_CUR_VER FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES HAR_ARTIFACT_VER(ARTIFACT_VERSION_ID);

CREATE TABLE HAR_MANIFEST (
 MANIFEST_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, MANIFEST_TYPE VARCHAR2(40) NOT NULL,
 STAGE_ID VARCHAR2(80), STATUS_CODE VARCHAR2(30) NOT NULL, MANIFEST_URI VARCHAR2(1000) NOT NULL,
 CONTENT_HASH VARCHAR2(80) NOT NULL, GATE_RESULT_ID VARCHAR2(80), CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_MANIFEST PRIMARY KEY (MANIFEST_ID),
 CONSTRAINT FK_HAR_MAN_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID)
);

CREATE TABLE HAR_MANIFEST_ITEM (
 MANIFEST_ID VARCHAR2(80) NOT NULL, ITEM_SEQ NUMBER(10) NOT NULL, ARTIFACT_ID VARCHAR2(80) NOT NULL,
 ARTIFACT_VERSION_ID VARCHAR2(90) NOT NULL, ITEM_ROLE VARCHAR2(40) NOT NULL, REQUIRED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
 CONSTRAINT PK_HAR_MANIFEST_ITEM PRIMARY KEY (MANIFEST_ID, ITEM_SEQ),
 CONSTRAINT FK_HAR_MI_MAN FOREIGN KEY (MANIFEST_ID) REFERENCES HAR_MANIFEST(MANIFEST_ID),
 CONSTRAINT FK_HAR_MI_ART FOREIGN KEY (ARTIFACT_ID) REFERENCES HAR_ARTIFACT(ARTIFACT_ID),
 CONSTRAINT FK_HAR_MI_VER FOREIGN KEY (ARTIFACT_VERSION_ID) REFERENCES HAR_ARTIFACT_VER(ARTIFACT_VERSION_ID),
 CONSTRAINT CK_HAR_MI_REQ CHECK (REQUIRED_YN IN ('Y','N'))
);
