-- NSIGHT AUTO HARNESS - TRACE / EVIDENCE / GATE / GOVERNANCE TABLES

CREATE TABLE HAR_SOURCE_EVIDENCE (
 SOURCE_EVIDENCE_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, SOURCE_TYPE VARCHAR2(40) NOT NULL,
 SOURCE_URI VARCHAR2(1000) NOT NULL, SOURCE_LOCATOR VARCHAR2(1000), CONTENT_HASH VARCHAR2(80) NOT NULL,
 EXCERPT_TEXT CLOB, CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_SOURCE_EVIDENCE PRIMARY KEY (SOURCE_EVIDENCE_ID),
 CONSTRAINT FK_HAR_SE_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID)
);

CREATE TABLE HAR_REQUIREMENT (
 REQUIREMENT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, REQUIREMENT_TYPE VARCHAR2(40) NOT NULL,
 TITLE VARCHAR2(500) NOT NULL, STATEMENT_TEXT CLOB NOT NULL, PRIORITY_CODE VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
 STATUS_CODE VARCHAR2(30) NOT NULL, ACCEPTANCE_CRITERIA CLOB, SOURCE_EVIDENCE_ID VARCHAR2(80), OWNER_ROLE VARCHAR2(80),
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_REQUIREMENT PRIMARY KEY (REQUIREMENT_ID),
 CONSTRAINT FK_HAR_REQ_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_REQ_SE FOREIGN KEY (SOURCE_EVIDENCE_ID) REFERENCES HAR_SOURCE_EVIDENCE(SOURCE_EVIDENCE_ID)
);

CREATE TABLE HAR_ASSUMPTION (
 ASSUMPTION_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, STATEMENT_TEXT CLOB NOT NULL,
 RISK_LEVEL VARCHAR2(20) NOT NULL, STATUS_CODE VARCHAR2(30) NOT NULL,
 REQUIRES_APPROVAL_YN CHAR(1) DEFAULT 'Y' NOT NULL, APPROVAL_ID VARCHAR2(80),
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_ASSUMPTION PRIMARY KEY (ASSUMPTION_ID),
 CONSTRAINT FK_HAR_ASM_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT CK_HAR_ASM_APPROVAL CHECK (REQUIRES_APPROVAL_YN IN ('Y','N'))
);

CREATE TABLE HAR_DOMAIN (
 DOMAIN_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, BUSINESS_CODE VARCHAR2(20) NOT NULL,
 DOMAIN_CODE VARCHAR2(80) NOT NULL, DOMAIN_NAME VARCHAR2(200) NOT NULL,
 OWNER_ORG_CODE VARCHAR2(50), DATA_OWNER_ORG_CODE VARCHAR2(50), STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_DOMAIN PRIMARY KEY (DOMAIN_ID),
 CONSTRAINT FK_HAR_DOMAIN_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT UK_HAR_DOMAIN_CODE UNIQUE (RUN_ID, BUSINESS_CODE, DOMAIN_CODE)
);

CREATE TABLE HAR_SERVICE_DEF (
 SERVICE_DEF_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, DOMAIN_ID VARCHAR2(80),
 SERVICE_ID VARCHAR2(200) NOT NULL, TRANSACTION_CODE VARCHAR2(80), PROCESSING_TYPE VARCHAR2(30) NOT NULL,
 BUSINESS_CODE VARCHAR2(20) NOT NULL, TIMEOUT_MS NUMBER(10), STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_SERVICE_DEF PRIMARY KEY (SERVICE_DEF_ID),
 CONSTRAINT FK_HAR_SVC_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_SVC_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES HAR_DOMAIN(DOMAIN_ID),
 CONSTRAINT UK_HAR_SVC_ID UNIQUE (RUN_ID, SERVICE_ID)
);

CREATE TABLE HAR_PROGRAM_COMP (
 PROGRAM_COMP_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, SERVICE_DEF_ID VARCHAR2(80),
 COMPONENT_TYPE VARCHAR2(30) NOT NULL, CLASS_NAME VARCHAR2(300) NOT NULL, PACKAGE_NAME VARCHAR2(500) NOT NULL,
 METHOD_NAME VARCHAR2(300), SOURCE_URI VARCHAR2(1000), STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_PROGRAM_COMP PRIMARY KEY (PROGRAM_COMP_ID),
 CONSTRAINT FK_HAR_PC_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_PC_SVC FOREIGN KEY (SERVICE_DEF_ID) REFERENCES HAR_SERVICE_DEF(SERVICE_DEF_ID)
);

CREATE TABLE HAR_SQL_STMT (
 SQL_STMT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, SERVICE_DEF_ID VARCHAR2(80),
 MAPPER_NAMESPACE VARCHAR2(500) NOT NULL, SQL_ID VARCHAR2(300) NOT NULL, OPERATION_TYPE VARCHAR2(20) NOT NULL,
 SOURCE_URI VARCHAR2(1000), STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_SQL_STMT PRIMARY KEY (SQL_STMT_ID),
 CONSTRAINT FK_HAR_SQL_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_SQL_SVC FOREIGN KEY (SERVICE_DEF_ID) REFERENCES HAR_SERVICE_DEF(SERVICE_DEF_ID),
 CONSTRAINT UK_HAR_SQL_ID UNIQUE (RUN_ID, MAPPER_NAMESPACE, SQL_ID)
);

CREATE TABLE HAR_DB_OBJECT (
 DB_OBJECT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, DOMAIN_ID VARCHAR2(80),
 OBJECT_OWNER VARCHAR2(100), OBJECT_NAME VARCHAR2(300) NOT NULL, OBJECT_TYPE VARCHAR2(30) NOT NULL,
 STATUS_CODE VARCHAR2(30) NOT NULL, CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_DB_OBJECT PRIMARY KEY (DB_OBJECT_ID),
 CONSTRAINT FK_HAR_DBO_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_DBO_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES HAR_DOMAIN(DOMAIN_ID),
 CONSTRAINT UK_HAR_DBO UNIQUE (RUN_ID, OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE)
);

CREATE TABLE HAR_TEST_CASE (
 TEST_CASE_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, TEST_TYPE VARCHAR2(30) NOT NULL,
 TEST_NAME VARCHAR2(500) NOT NULL, SOURCE_URI VARCHAR2(1000), STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_TEST_CASE PRIMARY KEY (TEST_CASE_ID),
 CONSTRAINT FK_HAR_TC_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID)
);

CREATE TABLE HAR_TRACE_LINK (
 TRACE_LINK_ID VARCHAR2(90) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL,
 SOURCE_TYPE VARCHAR2(50) NOT NULL, SOURCE_ID VARCHAR2(100) NOT NULL,
 TARGET_TYPE VARCHAR2(50) NOT NULL, TARGET_ID VARCHAR2(100) NOT NULL,
 RELATION_TYPE VARCHAR2(40) NOT NULL, CONFIDENCE_SCORE NUMBER(5,2), STATUS_CODE VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_TRACE_LINK PRIMARY KEY (TRACE_LINK_ID),
 CONSTRAINT FK_HAR_TRACE_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT UK_HAR_TRACE UNIQUE (RUN_ID,SOURCE_TYPE,SOURCE_ID,TARGET_TYPE,TARGET_ID,RELATION_TYPE)
);

CREATE TABLE HAR_EXEC_EVIDENCE (
 EXEC_EVIDENCE_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, TASK_ID VARCHAR2(80),
 EVIDENCE_TYPE VARCHAR2(50) NOT NULL, EVIDENCE_URI VARCHAR2(1000) NOT NULL, CONTENT_HASH VARCHAR2(80) NOT NULL,
 COMMAND_TEXT CLOB, EXIT_CODE NUMBER(10), STARTED_AT TIMESTAMP(6) WITH TIME ZONE, ENDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_EXEC_EVIDENCE PRIMARY KEY (EXEC_EVIDENCE_ID),
 CONSTRAINT FK_HAR_EE_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_EE_TASK FOREIGN KEY (TASK_ID) REFERENCES HAR_AGENT_TASK(TASK_ID)
);

CREATE TABLE HAR_TOOL_INVOCATION (
 TOOL_INVOCATION_ID VARCHAR2(90) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, TASK_ID VARCHAR2(80),
 TOOL_NAME VARCHAR2(200) NOT NULL, TOOL_VERSION VARCHAR2(100), ARGUMENTS_HASH VARCHAR2(80), RESULT_HASH VARCHAR2(80),
 STATUS_CODE VARCHAR2(30) NOT NULL, STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 ENDED_AT TIMESTAMP(6) WITH TIME ZONE, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_TOOL_INVOCATION PRIMARY KEY (TOOL_INVOCATION_ID),
 CONSTRAINT FK_HAR_TI_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_TI_TASK FOREIGN KEY (TASK_ID) REFERENCES HAR_AGENT_TASK(TASK_ID)
);

CREATE TABLE HAR_GATE_DEF (
 GATE_ID VARCHAR2(40) NOT NULL, GATE_VERSION VARCHAR2(30) NOT NULL, GATE_NAME VARCHAR2(200) NOT NULL,
 RULESET_URI VARCHAR2(1000) NOT NULL, CONTENT_HASH VARCHAR2(80) NOT NULL,
 STATUS_CODE VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL, REQUIRED_APPROVALS NUMBER(5) DEFAULT 0 NOT NULL,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_GATE_DEF PRIMARY KEY (GATE_ID,GATE_VERSION)
);

CREATE TABLE HAR_GATE_RESULT (
 GATE_RESULT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, RUN_STAGE_ID VARCHAR2(70),
 GATE_ID VARCHAR2(40) NOT NULL, GATE_VERSION VARCHAR2(30) NOT NULL, DECISION_CODE VARCHAR2(30) NOT NULL,
 QUALITY_SCORE NUMBER(5,2), HARD_FAILURE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
 REQUIRED_FAILURE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
 EVALUATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 EVALUATED_BY VARCHAR2(100) NOT NULL, SUMMARY_TEXT VARCHAR2(4000),
 CONSTRAINT PK_HAR_GATE_RESULT PRIMARY KEY (GATE_RESULT_ID),
 CONSTRAINT FK_HAR_GR_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_GR_STAGE FOREIGN KEY (RUN_STAGE_ID) REFERENCES HAR_RUN_STAGE(RUN_STAGE_ID),
 CONSTRAINT FK_HAR_GR_GATE FOREIGN KEY (GATE_ID,GATE_VERSION) REFERENCES HAR_GATE_DEF(GATE_ID,GATE_VERSION)
);
ALTER TABLE HAR_MANIFEST ADD CONSTRAINT FK_HAR_MAN_GATE_RESULT FOREIGN KEY (GATE_RESULT_ID) REFERENCES HAR_GATE_RESULT(GATE_RESULT_ID);

CREATE TABLE HAR_RULE_RESULT (
 RULE_RESULT_ID VARCHAR2(90) NOT NULL, GATE_RESULT_ID VARCHAR2(80) NOT NULL, RULE_ID VARCHAR2(150) NOT NULL,
 RULE_TYPE VARCHAR2(30) NOT NULL, STATUS_CODE VARCHAR2(30) NOT NULL, SCORE_VALUE NUMBER(7,2),
 SEVERITY_CODE VARCHAR2(20), MESSAGE_TEXT VARCHAR2(4000), EVIDENCE_REF VARCHAR2(1000),
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_RULE_RESULT PRIMARY KEY (RULE_RESULT_ID),
 CONSTRAINT FK_HAR_RR_GATE FOREIGN KEY (GATE_RESULT_ID) REFERENCES HAR_GATE_RESULT(GATE_RESULT_ID),
 CONSTRAINT UK_HAR_RR_RULE UNIQUE (GATE_RESULT_ID,RULE_ID)
);

CREATE TABLE HAR_APPROVAL (
 APPROVAL_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, GATE_RESULT_ID VARCHAR2(80),
 APPROVAL_TYPE VARCHAR2(50) NOT NULL, REQUIRED_ROLE VARCHAR2(80) NOT NULL, APPROVER_ID VARCHAR2(100),
 DECISION_CODE VARCHAR2(30) NOT NULL, COMMENT_TEXT VARCHAR2(4000),
 REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
 CREATED_BY VARCHAR2(100) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_APPROVAL PRIMARY KEY (APPROVAL_ID),
 CONSTRAINT FK_HAR_AP_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_AP_GATE FOREIGN KEY (GATE_RESULT_ID) REFERENCES HAR_GATE_RESULT(GATE_RESULT_ID)
);
ALTER TABLE HAR_ASSUMPTION ADD CONSTRAINT FK_HAR_ASM_APPROVAL FOREIGN KEY (APPROVAL_ID) REFERENCES HAR_APPROVAL(APPROVAL_ID);

CREATE TABLE HAR_EXCEPTION_APPROVAL (
 EXCEPTION_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, RULE_ID VARCHAR2(150) NOT NULL,
 SCOPE_TEXT VARCHAR2(2000) NOT NULL, REASON_TEXT CLOB NOT NULL, RISK_TEXT CLOB NOT NULL,
 COMPENSATING_CONTROL CLOB NOT NULL, OWNER_ID VARCHAR2(100) NOT NULL, APPROVER_ID VARCHAR2(100) NOT NULL,
 STATUS_CODE VARCHAR2(30) NOT NULL, EFFECTIVE_FROM TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_HAR_EXCEPTION PRIMARY KEY (EXCEPTION_ID),
 CONSTRAINT FK_HAR_EX_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID)
);

CREATE TABLE HAR_ISSUE (
 ISSUE_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL, ISSUE_TYPE VARCHAR2(50) NOT NULL,
 SEVERITY_CODE VARCHAR2(20) NOT NULL, TITLE VARCHAR2(500) NOT NULL, DESCRIPTION_TEXT CLOB,
 STATUS_CODE VARCHAR2(30) NOT NULL, OWNER_ID VARCHAR2(100), DUE_AT TIMESTAMP(6) WITH TIME ZONE,
 SOURCE_GATE_RESULT_ID VARCHAR2(80), CREATED_BY VARCHAR2(100) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR2(100) NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_HAR_ISSUE PRIMARY KEY (ISSUE_ID),
 CONSTRAINT FK_HAR_ISSUE_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID),
 CONSTRAINT FK_HAR_ISSUE_GATE FOREIGN KEY (SOURCE_GATE_RESULT_ID) REFERENCES HAR_GATE_RESULT(GATE_RESULT_ID)
);

CREATE TABLE HAR_DRIFT_ISSUE (
 DRIFT_ID VARCHAR2(80) NOT NULL, RUN_ID VARCHAR2(50) NOT NULL,
 BASELINE_OBJECT_TYPE VARCHAR2(50) NOT NULL, BASELINE_OBJECT_ID VARCHAR2(100) NOT NULL,
 ACTUAL_OBJECT_TYPE VARCHAR2(50) NOT NULL, ACTUAL_OBJECT_ID VARCHAR2(100), DRIFT_TYPE VARCHAR2(50) NOT NULL,
 SEVERITY_CODE VARCHAR2(20) NOT NULL, DIFFERENCE_TEXT CLOB NOT NULL, STATUS_CODE VARCHAR2(30) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
 CONSTRAINT PK_HAR_DRIFT PRIMARY KEY (DRIFT_ID),
 CONSTRAINT FK_HAR_DRIFT_RUN FOREIGN KEY (RUN_ID) REFERENCES HAR_RUN(RUN_ID)
);

CREATE TABLE HAR_AUDIT_LOG (
 AUDIT_ID VARCHAR2(90) NOT NULL, EVENT_TIME TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 EVENT_TYPE VARCHAR2(80) NOT NULL, PROJECT_ID VARCHAR2(40), RUN_ID VARCHAR2(50), TASK_ID VARCHAR2(80),
 ACTOR_TYPE VARCHAR2(30) NOT NULL, ACTOR_ID VARCHAR2(200) NOT NULL,
 RESOURCE_TYPE VARCHAR2(50), RESOURCE_ID VARCHAR2(200), BEFORE_HASH VARCHAR2(80), AFTER_HASH VARCHAR2(80),
 DETAIL_URI VARCHAR2(1000), TRACE_ID VARCHAR2(100),
 CONSTRAINT PK_HAR_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

CREATE TABLE HAR_OUTBOX_EVENT (
 OUTBOX_EVENT_ID VARCHAR2(90) NOT NULL, AGGREGATE_TYPE VARCHAR2(80) NOT NULL, AGGREGATE_ID VARCHAR2(100) NOT NULL,
 EVENT_TYPE VARCHAR2(100) NOT NULL, PAYLOAD_TEXT CLOB NOT NULL, STATUS_CODE VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
 OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
 RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL, NEXT_RETRY_AT TIMESTAMP(6) WITH TIME ZONE,
 CONSTRAINT PK_HAR_OUTBOX_EVENT PRIMARY KEY (OUTBOX_EVENT_ID),
 CONSTRAINT CK_HAR_OUTBOX_STATUS CHECK (STATUS_CODE IN ('PENDING','PUBLISHING','PUBLISHED','FAILED','DEAD'))
);
